# Pseudo image creating script
# using a syntax similar to Dockerfile

FROM JS-API-Featured-CentOS7-May-20-2019

RUN yum install https://repo.opensciencegrid.org/osg/3.4/osg-3.4-el7-release-latest.rpm
RUN yum install epel-release yum-plugin-priorities
RUN yum install osg-oasis osg-wn-client condor
RUN yum install singularity
RUN yum update

# configure singularity
# see https://opensciencegrid.org/docs/worker-node/install-singularity/#singularity-via-rpm
RUN sed -i 's/enable overlay = try/enable overlay = no/' /etc/singularity/singularity.conf

ADD add_ce_user.sh /usr/bin/add_ce_users.sh
RUN /usr/bin/add_ce_users.sh

ADD 98_security.config /etc/condor/config.d/98_security.config 
ADD 99_daemons.config /etc/condor/config.d/99_daemons.config
ADD 50_condor_host.config /etc/condor/config.d/50_condor_host.config

# get the same one as at the collector
ADD pool_password /etc/condor/pool_password

# We are assuming a specific IP and DNS name, update as needed
RUN echo "10.1.1.13   osg-ce-collector osg-ce-collector.osg.jetstream-cloud.org" >> /etc/hosts
RUN echo "10.1.1.14   osg-ce-squid osg-ce-squid.osg.jetstream-cloud.org" >> /etc/hosts

RUN echo "/cvmfs /etc/auto.cvmfs" > /etc/auto.master.d/cvmfs.autofs
ADD cvmfs.d/default.local /etc/cvmfs/default.local

RUN systemctl enable autofs
RUN systemctl start autofs

RUN systemctl enable condor
RUN systemctl start condor

