# Pseudo image creating script
# using a syntax similar to Dockerfile

FROM JS-API-Featured-CentOS7-May-20-2019

RUN yum install https://repo.opensciencegrid.org/osg/3.4/osg-3.4-el7-release-latest.rpm
RUN yum install epel-release yum-plugin-priorities
RUN yum install condor
RUN yum update


ADD 98_security.config /etc/condor/config.d/98_security.config 
ADD 99_daemons.config /etc/condor/config.d/99_daemons.config

ADD pool_password /etc/condor/pool_password

# We are assuming a specific IP and DNS name, update as needed
RUN echo "osg-ce-collector.osg.jetstream-cloud.org" > /etc/hostname
RUN echo "10.1.1.13   osg-ce-collector osg-ce-collector.osg.jetstream-cloud.org" >> /etc/hosts

RUN systemctl enable condor
RUN systemctl start condor

